name: example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

  drift_pagination:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
