name: drift_pagination
description: "A package for pagination with Drift."
repository: https://github.com/MarshRadijiu/drift_pagination
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  drift: ^2.26.1
